server {
listen 80;

location / {
root /usr/share/nginx/html;
index index.html index.htm;
try_files $uri $uri/ /index.html;
}

    location /api/OpenELIS-Global/ {
        resolver 127.0.0.11 valid=30s;
        set $backend_upstream http://oe.openelis.org:8080;
        rewrite ^/api/OpenELIS-Global/(.*)$ /OpenELIS-Global/$1 break;
        proxy_pass $backend_upstream;

proxy_cookie_path /OpenELIS-Global /api/OpenELIS-Global;

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
}
}